### ISSUE TITLE
Comment in .env breaks build process

### ISSUE THREAD

**Issue by RafnexJr** [CptOfEvilMinions/FleetDM-Automation#17]
Your comments in the `.env` file about the Log4j introduce a space which is included in the variable. This breaks the build process with docker compose 

```
#docker-compose build

Building fleet
Step 1/17 : ARG FLEETDM_VERSION
Step 2/17 : FROM fleetdm/fleet:v${FLEETDM_VERSION}
ERROR: Service 'fleet' failed to build: invalid reference format
```

Either remove the comments or place them on a separate line, tested it with this:

```
# Log4Shell CVE not detected
FLEETDM_VERSION=4.7.0
# Log4Shell CVE not detected
NGINX_VERSION=1.21.4-alpine
# Log4Shell CVE not detected
FLEETDM_MYSQL_VERSION=8.0.27
# Log4Shell CVE not detected
```

Thanks for the greate work, cheers :)

**Comment by CptOfEvilMinions** [comment]
Hey @RafnexJr, 

Thanks for bringing this to my attention. I am going to be cutting a `v4.8.0` release later this week that fix this.

**Comment by CptOfEvilMinions** [comment]
https://github.com/CptOfEvilMinions/FleetDM-Automation/pull/18/files#diff-e9cbb0224c4a3d23a6019ba557e0cd568c1ad5e1582ff1e335fb7d99b7a1055d
