### ISSUE TITLE
Dockerfile-FleetDM won't build

### ISSUE THREAD

**Issue by kovacs-andras** [CptOfEvilMinions/FleetDM-Automation#2]
Hi!
Many thanks for all your work!

IMHO this useradd:
https://github.com/CptOfEvilMinions/FleetDM-Automation/blob/main/docker/Dockerfile-FleetDM#L9-L10
will fail because the user in the base image now is:
uid=100(fleet) gid=101(fleet) groups=101(fleet)
So you should switch to user root or sg. similar.

Regards,

**Comment by CptOfEvilMinions** [comment]
Thanks for the update. At the time when I created the Dockerfile there was only the root user.

**Comment by CptOfEvilMinions** [comment]
Hey @kovacs-andras,

Thanks for raising awareness about this issue. In my latest commit, I have fixed this issue.

**Comment by CptOfEvilMinions** [comment]
Latest commit fixed this issue
